#pragma once
//통신 프로토콜 
typedef enum SC_PROTOCOL_
{
	SC_NONE,
	SC_ROGIN_SUCC,
	SC_ROGIN_FAIL,
	SC_PUT_PLAYER,
	SC_NOT_MY_VIEW,
	SC_LOG_OUT_PLAYER,
	SC_PLAYER_MOVE,
	SC_PLAYER_MOVE_SYNC,
	SC_PLAYER_ATTACK,
	SC_PLAYER_NOT_ACT
}SC_PROTOCOL;

typedef enum CS_PROTOCOL_
{
	CS_NONE,
	CS_REQ_ROGIN,
	CS_PLAYER_MOVE,
	CS_PLAYER_ATTACK,
	CS_PLAYER_NOT_ACT
}CS_PROTOCOL;
